CUNADO_CHISTES_GASTOS = [
    "¡Bah, si esto lo paga el niño con la beca!",
    "Esto en pesetas era menos, ¿eh?",
    "Gastar es invertir… en felicidad.",
    "Si Hacienda no lo ve, no cuenta.",
    "Esto es una necesidad básica. Como el WiFi.",
    "Con lo que he ahorrado en el Black Friday, me puedo comprar otro.",
    "¡Eso lo paga el banco… de mi suegro!",
    "Total, una vez al año no hace daño. Aunque sea la quinta vez este mes.",
    "¿Caro? ¡Caro es no disfrutar la vida!",
    "Para lo que vamos a vivir…",
    "Esto se amortiza solo. Algún día.",
    "Lo meto como gasto médico. Por salud mental.",
    "Pide ticket regalo, que luego lo devuelvo.",
    "¡Si es por los puntos de la tarjeta!",
    "No es capricho, es inversión en autoestima.",
    "Invito yo... con tu cuenta.",  
    "Hacienda somos todos... pero paga tú.",  
    "¿La cuenta? Que la pague el IVA... y tu sueldo.",  
    "Yo ahorro... en las rondas.",  
    "Paga el que más gana... o sea, tú.",  
    "Hacienda me persigue... igual que esta factura.",  
    "Yo ya pagué... en sueños.",  
    "Niño, pide prestado... y no devuelvas.",  
    "Si pagas tú, Hacienda te devuelve... risas.",  
    "Yo pongo los chistes... tú los euros.",
    "Esto con la academia te lo deduces facilito...",   ### A partir de aquí supuestamente son más fuertes
    "¿Otro gasto? Mira, lo tuyo ya no es economía, es un caso clínico.",  
    "Tú no administras dinero, tú lo liberas como si fuera palomas.",
    "Con esta gestión, tu plan de jubilación es la beneficencia.",
    "Si te pagaran por gastar, ya serías Elon Musk… pero sin talento.",
    "No es un gasto, es una forma lenta de autodestrucción financiera.",
    "Lo tuyo no es vivir por encima de tus posibilidades, es cavar con pala prestada.",
    "¿Control financiero? Tú te manejas con el 'a ver qué pasa'.",
    "Cada vez que compras algo, tu cuenta llora y tu futuro también.",
    "No es un capricho, es otro clavo en el ataúd de tu solvencia.",
    "Sigue así y pronto pagarás el pan a plazos. Con intereses.",
    "No inviertes, no gastas, tú saboteas tu economía con pasión.",
    "Si existiera un reality de ruina personal, tú ya ganabas la final.",
    "Te va a llamar Hacienda para darte un abrazo. Por pena.",
    "Tú no gastas, tú haces arqueología bancaria: dejas ruinas.",
    "Ya no es un gasto, es una declaración de guerra al sentido común.",
    "Tu cuenta corriente arde. Literalmente."
]

FRASES_PEDIR_GASTO = [
    "Venga, confiesa... ¿cuánto te has fundido esta vez?",
    "No te preocupes, aquí nadie juzga... salvo tu cuenta bancaria.",
    "Introduce el importe del sablazo. Sin miedo.",
    "¿Cuánto ha costado tu última alegría con forma de deuda?",
    "Dame la cifra. La terapia financiera empieza por aceptar el gasto.",
    "No es tarde para arrepentirte, pero necesito el número igual.",
    "Sé valiente. ¿Cuánto ha dolido (en euros)?",
    "El banco ya lo sabe. Yo solo lo quiero por escrito.",
    "Vamos con sinceridad: ¿cuánto has hecho sufrir a tu tarjeta?",
    "Anota el daño económico. Respiramos juntos, ¿vale?",
    "Introduce el número. Yo pongo la compasión.",
    "¿De cuánto ha sido la multa?"
]

CUNADO_CHISTES_INGRESO = [
    "¡Vamos, que hoy se cena con postre!",
    "Esto ya parece el sueldo de un futbolista. De tercera regional, pero futbolista.",
    "¡El niño ya es autosuficiente! Bueno, casi.",
    "Si Hacienda pregunta, es un regalo.",
    "Otro ingreso y sigo sin ser millonario. Algo falla.",
    "Esto va directo al colchón... del banco.",
    "¡No lo toques que eso es pa' los impuestos!",
    "Voy a invertirlo... en una caña.",
    "Por fin entra algo que no sea un cobro.",
    "¡Soy rico! (Hasta que mire los recibos del mes)",
    "Esto compensa los cafés de la semana. Casi.",
    "Lo meto en la cuenta ahorro-por-si-acaso.",
    "Ahora sí que sí, ¡nos vamos a Andorra! (de visita)",
    "Voy a enmarcar el pantallazo del ingreso.",
    "¡Este mes no vendo un riñón!",
    "¿Ingreso? ¿Seguro que no es un error del banco?",
    "Esto ya es sueldo de influencer. Pero de los que nadie sigue.",
    "No te emociones. En cuanto pises la calle, ya es gasto.",
    "Te ha ingresado dinero alguien. Probablemente por lástima.",
    "Con esto y un rasca del kiosko, igual cenas caliente.",
    "Otro ingreso testimonial. Pero mira, es tuyo. De momento.",
    "A este paso en 2075 te compras un piso. En Marte.",
    "Esto es lo que se llama una alegría fiscal efímera.",
    "Entra el dinero por transferencia y se va por domiciliación. Eficiencia alemana.",
    "Te ingresan uno y ya te crees Warren Buffett. Baja, que te vas a marear.",
    "¿Ingreso? Cuidado que igual te da para invitar a un café. Sin leche.",
    "Por fin entra algo que no es un cobro. Brindemos. Mentalmente.",
    "Súbelo a Instagram. #IngresoReal #NoEsBroma",
    "Esto es gasolina para tus ilusiones. Y para pagar la gasolina real.",
    "¡Ingreso recibido! Que su estancia en tu cuenta sea breve pero digna.",
    "Ocultaselo a Hacienda, son los malos de la película",
    "¡Que bien! Una pena que la mitad sea para Hacienda...",
    "¿Y a mi cuanto me toca?",
    "Mira, no es mucho, pero al menos no es Hacienda pidiendo. Eso ya es ganar.", ### A partir de aquí supuestamente son más fuertes
    "¿Ingreso? ¿Y ya te crees Rockefeller? Si no te llega ni para Netflix compartido.",
    "Con esto no sales de pobre, pero te da para creértelo media hora.",
    "Otro ingreso simbólico. Lo justo para ilusionarte y arruinarte después.",
    "Esa transferencia es como tú: pequeña, inútil y tarde.",
    "Más que ingreso, parece limosna. Pero tú dale las gracias igual.",
    "Entra el dinero y ya sueñas con reformar el baño. Spoiler: no te llega ni para el felpudo.",
    "¿Ingreso? Quédate con el pantallazo, porque va a durar menos que tus propósitos de año nuevo.",
    "Con lo que cobras, ni la inflación se molesta en afectarte.",
    "Este ingreso es tan inútil que ni Hacienda se va a molestar en robártelo.",
    "Ya puedes celebrar: este mes comerás arroz... con esperanza.",
    "No sé qué da más pena, el importe o que lo llames ingreso.",
    "Tú no tienes nómina, tienes notificaciones de lástima bancaria.",
    "Un ingreso más y ya te crees estable. Tranquilo, la factura del gas te baja de la nube.",
    "Súbelo a redes con hashtag: #MilagroFinanciero #Duró5Minutos",
    "Con este ritmo, te independizas… a los 83. Con suerte."
]

FRASES_PEDIR_INGRESO = [
    "¿Cuánto te han soltado? Que no cunda el pánico, no lo vamos a gastar (aún).",
    "Introduce el ingreso y disfruta este momento fugaz de felicidad.",
    "No todos los días se gana algo. ¡Anótalo antes de que se evapore!",
    "¿Te han pagado? Vamos, comparte la buena nueva (en euros).",
    "Dame el número mágico antes de que se lo coma una suscripción.",
    "Importe del ingreso, por favor. Aprovecha antes de que Hacienda lo huela.",
    "Sé generoso con la cifra…, que ya bastante escasa es.",
    "Vamos, presume un poco. ¿Cuánto te ha caído?",
    "Haz memoria… ¿cuánto te ingresaron por fin?",
    "Rellena el importe. Hoy no duele, hoy alegra.",
    "Anota el botín. Hoy te ha tocado ser el rico del grupo."
]

EMOJIS_GASTOS = [
    "💸", "🧾", "🧠", "📉", "🥴", "🚨", "👛",
    "🧘‍♂️", "🎯", "📦", "🥲", "🔥", "📊", "🔄", "🎁"
]

EMOJIS_INGRESOS = [
    "💰", "📈", "🤑", "🎉", "💸", "🍾", "📬",
    "👀", "💼", "🥂", "🔔", "🙌", "🚀", "🧾", "📥"
]